# Stage 1: Build and test
FROM node:18.20.2 as builder
WORKDIR /app
COPY --chown=node:node ["package.json", "package-lock.json", "./"]
RUN npm install
COPY --chown=node:node ["server.js", "./"]
COPY --chown=node:node ["models/Lookup.js", "./models/Lookup.js"]

# Stage 2: Production image
FROM node:18-slim
WORKDIR /app
COPY --from=builder /app /app
COPY --chown=node:node ["package.json", "package-lock.json", "server.js", "start.js", "./"]
RUN npm install
EXPOSE 3000
CMD ["node", "start.js"]
