services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.scratch
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ipToolkit
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: ipToolkit
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
