name: Terraform Document
on:
  pull_request:
    branches: [main]
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      id: checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GH_ACCESS_TOKEN }}
        fetch-depth: 0
    - name: Terraform Documentation
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: ./infras/terraform/modules/
        config-file: ./terraform-docs.yml
        git-push: true
